export const COMPONENT_GROUPS = [
  {
    items: [
      { id: 'accordion', label: 'Accordion' },
      { id: 'app-layout', label: 'AppLayout' },
      { id: 'badge', label: 'Badge' },
      { id: 'blockquote', label: 'Blockquote' },
      { id: 'breadcrumbs', label: 'Breadcrumbs' },
      { id: 'button', label: 'Button' },
      { id: 'card', label: 'Card' },
      { id: 'chip', label: 'Chip' },
      { id: 'code-block', label: 'CodeBlock' },
      { id: 'copy-to-clipboard', label: 'CopyToClipboard' },
      { id: 'dropdown-menu', label: 'DropdownMenu' },
      { id: 'error-message', label: 'ErrorMessage' },
      { id: 'footer', label: 'Footer' },
      { id: 'grid', label: 'Grid' },
      { id: 'header', label: 'Header' },
      { id: 'hero', label: 'Hero' },
      { id: 'input', label: 'Input' },
      { id: 'list', label: 'List' },
      { id: 'loading-indicator', label: 'LoadingIndicator' },
      { id: 'modal', label: 'Modal' },
      { id: 'nav', label: 'Nav' },
      { id: 'nav-menu', label: 'NavMenu' },
      { id: 'notification-bar', label: 'NotificationBar' },
      { id: 'prose', label: 'Prose' },
      { id: 'radio-button', label: 'RadioButton' },
      { id: 'scroll-to-top', label: 'ScrollToTop' },
      { id: 'section', label: 'Section' },

      { id: 'side-nav', label: 'SideNav' },
      { id: 'split-panel', label: 'SplitPanel' },
      { id: 'table', label: 'Table' },
      { id: 'tabs', label: 'Tabs' },
      { id: 'table-of-contents', label: 'TableOfContents' },
      { id: 'textarea', label: 'Textarea' },
      { id: 'theme-toggle', label: 'ThemeToggle' },
      { id: 'toggle', label: 'Toggle' },
      { id: 'toast', label: 'Toast' },
      { id: 'tooltip', label: 'Tooltip' },
      { id: 'tools-panel', label: 'ToolsPanel' },
    ],
  },
];
