// Generated by scripts/build-icons.mjs — do not edit directly
import type { SVGProps } from 'react';

const Moon = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 200 200"
    width="1em"
    height="1em"
    aria-hidden="true"
    focusable="false"
    {...props}
  >
    <g transform="translate(100, 100)">
    <path d="M 22 -45 A 50 50 0 1 0 22 45 A 45 45 0 1 1 22 -45 Z" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
  </g>
  </svg>
);

Moon.displayName = 'Moon';
export default Moon;
