// Generated by scripts/build-icons.mjs — do not edit directly
import type { SVGProps } from 'react';

const Sun = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 200 200"
    width="1em"
    height="1em"
    aria-hidden="true"
    focusable="false"
    {...props}
  >
    <g transform="translate(100, 100)">
    <circle cx="0" cy="0" r="35" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="0" y1="-55" x2="0" y2="-75" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="0" y1="55" x2="0" y2="75" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="-55" y1="0" x2="-75" y2="0" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="55" y1="0" x2="75" y2="0" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="-35" y1="-35" x2="-50" y2="-50" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="35" y1="35" x2="50" y2="50" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="-35" y1="35" x2="-50" y2="50" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="35" y1="-35" x2="50" y2="-50" fill="none" stroke="currentColor" strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>
  </g>
  </svg>
);

Sun.displayName = 'Sun';
export default Sun;
