/**
 * Icon codegen: src/icons/svgs/*.svg → src/icons/{name}.tsx + src/icons/index.ts
 *
 * Rules for source SVGs:
 *   - No background <rect> elements
 *   - Use currentColor OR any color value (script replaces all non-"none" colors with currentColor)
 *   - viewBox must be set on the <svg> element
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SVG_DIR  = path.resolve(__dirname, '../src/icons/svgs');
const TSX_DIR  = path.resolve(__dirname, '../src/icons/tsx');
const IDX_FILE = path.resolve(__dirname, '../src/icons/index.ts');

// ─── Attribute name conversions (SVG → React JSX) ────────
const ATTR_MAP = {
  'stroke-width':      'strokeWidth',
  'stroke-linecap':    'strokeLinecap',
  'stroke-linejoin':   'strokeLinejoin',
  'stroke-dasharray':  'strokeDasharray',
  'stroke-dashoffset': 'strokeDashoffset',
  'stroke-miterlimit': 'strokeMiterlimit',
  'fill-rule':         'fillRule',
  'clip-rule':         'clipRule',
  'clip-path':         'clipPath',
  'stop-color':        'stopColor',
  'stop-opacity':      'stopOpacity',
  'color-interpolation-filters': 'colorInterpolationFilters',
  'class':             'className',
};

function toReactAttrs(str) {
  return Object.entries(ATTR_MAP).reduce(
    (s, [from, to]) => s.replace(new RegExp(`\\b${from}=`, 'g'), `${to}=`),
    str
  );
}

// Replace any hardcoded fill/stroke color (hex, rgb, named) with currentColor.
// Preserves fill="none", stroke="none", fill="transparent".
function replaceColors(str) {
  return str.replace(
    /\b(fill|stroke)="(?!none\b|transparent\b)([^"]+)"/g,
    '$1="currentColor"'
  );
}

// Remove xmlns declarations from inner content (React handles the SVG namespace)
function stripXmlns(str) {
  return str.replace(/\s+xmlns(?::\w+)?="[^"]*"/g, '');
}

// kebab-case or snake_case → PascalCase
function toPascalCase(str) {
  return str
    .replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase())
    .replace(/^([a-z])/, c => c.toUpperCase());
}

// ─── Main ─────────────────────────────────────────────────
if (!fs.existsSync(SVG_DIR)) {
  console.error(`SVG source directory not found: ${SVG_DIR}`);
  process.exit(1);
}
if (!fs.existsSync(TSX_DIR)) fs.mkdirSync(TSX_DIR, { recursive: true });

const svgFiles = fs.readdirSync(SVG_DIR).filter(f => f.endsWith('.svg')).sort();

if (svgFiles.length === 0) {
  console.log('No SVG files found in src/icons/svgs/ — nothing to generate.');
  process.exit(0);
}

const generated = [];

for (const file of svgFiles) {
  const baseName = path.basename(file, '.svg');       // e.g. "arrow-right"
  const componentName = toPascalCase(baseName);        // e.g. "ArrowRight"
  const outFile = `${baseName}.tsx`;

  const raw = fs.readFileSync(path.join(SVG_DIR, file), 'utf8');

  // Extract viewBox
  const viewBoxMatch = raw.match(/viewBox="([^"]+)"/);
  if (!viewBoxMatch) {
    console.warn(`  ⚠  ${file}: no viewBox found — skipping`);
    continue;
  }
  const viewBox = viewBoxMatch[1];

  // Extract inner SVG content
  const innerMatch = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>\s*$/);
  if (!innerMatch) {
    console.warn(`  ⚠  ${file}: could not parse SVG content — skipping`);
    continue;
  }

  let inner = innerMatch[1].trim();
  inner = replaceColors(inner);
  inner = toReactAttrs(inner);
  inner = stripXmlns(inner);

  const tsx =
`// Generated by scripts/build-icons.mjs — do not edit directly
import type { SVGProps } from 'react';

const ${componentName} = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="${viewBox}"
    width="1em"
    height="1em"
    aria-hidden="true"
    focusable="false"
    {...props}
  >
    ${inner}
  </svg>
);

${componentName}.displayName = '${componentName}';
export default ${componentName};
`;

  fs.writeFileSync(path.join(TSX_DIR, outFile), tsx, 'utf8');
  generated.push({ baseName, componentName });
  console.log(`  ✓  ${file.padEnd(24)} →  tsx/${outFile}`);
}

// ─── Barrel index.ts ──────────────────────────────────────
const barrel =
`// Generated by scripts/build-icons.mjs — do not edit directly
${generated.map(({ baseName, componentName }) =>
  `export { default as ${componentName} } from './tsx/${baseName}';`
).join('\n')}
`;

fs.writeFileSync(IDX_FILE, barrel, 'utf8');
console.log(`\n  ✓  index.ts updated — ${generated.length} icon${generated.length === 1 ? '' : 's'} total`);
